# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20161115_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
